- name: variables to print
  hosts: web
  vars: 
    COURSE: "DevOps with AWS from PLAY level"
    DURATION: "120HRS"
    TRAINER: "Sivakumar Reddy M"
  vars_prompt: 
  - name: COURSE
    prompt: please enter the course name 
    private: false # not confidental 
  tasks: 
  - name: print the information
    vars: 
    COURSE: "DevOps with AWS from TASK level"
    DURATION: "120HRS"
    TRAINER: "Sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "HI, I am learning {{COURSE}}"