- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check the user exist or not
    ansible.builtin.command:
    register: USER #here USER is a variable that gets the output

  - name: print the user information
    ansible.builtin.debug:
      msg: "user info: {{ user }}"  